export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE="CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_ID_REQUEST="GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS="GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILURE="GET_ORDER_BY_ID_FAILURE"




export const UPDATE_CART_ITEM_REQUEST="UPDATE_CART_ITEM_REQUEST"
export const UPDATE_CART_ITEM_SUCCESS="UPDATE_CART_ITEM_SUCCESS"
export const UPDATE_CART_ITEM_FAILURE="UPDATE_CART_ITEM_FAILURE"
